version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: admin
      ports:
        - "5432:5432"
      volumes:
        - dbs:/var/lib/postgresql/data/

    nginx:
        container_name: nginx-container        
        build: ./nginx
        restart: always
        ports:
        - "8080:80" 
        volumes:        
        - project_data:/docker_project1    
        - project_data2:/docker_project2        
        - ./log:/var/log/nginx              
        depends_on:
        - sport_project1
        - sport_project2
        
    sport_project1:
        container_name: host_1
        build: ./sport_project1        
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi.ini         
        ports:
        - "8002:8000"
        volumes:
        - project_data:/docker_project1        
        depends_on:
        - db

    sport_project2:        
        container_name: host_2
        build: ./sport_project2        
        restart: always
        # command: uwsgi  --emperor uwsgi.ini         
        command: uwsgi --ini uwsgi2.ini         
        ports:
        - "8003:8001"
        volumes:
        - project_data2:/docker_api2        
        depends_on:
        - db

volumes:
    project_data:
    project_data2:
    dbs:

